/** @type {import('next').NextConfig} */
const nextConfig = {
    metadata : {
        title: "DanBrown Clone",
        description: "Generated by create next app",
      },
      output: "export",
      images: {
        unoptimized: true,
      }
};

export default nextConfig;
