/** @type {import('next').NextConfig} */
const nextConfig = {
    metadata : {
        title: "DanBrown Clone",
        description: "Generated by create next app",
      }
};

export default nextConfig;
