name: Deploy to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      

      - name: Deploy to StackCP via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com 
          username: stephenkingacademy.com 
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22 
          script: |
            cd /home/stephenkingacademy.com/public_html
            rm -rf *
            mkdir -p .next
            rsync -avz .next ./
            rsync -avz public ./
            rsync -avz package.json ./
            rsync -avz next.config.js ./
            npm install --omit=dev
            pm2 restart all # Or your start command