name: Deploy to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Recommended stable version for Next.js

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build  # This generates the static files and assets

      - name: Deploy to StackCP via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com
          username: stephenkingacademy.com  # Adjust this with your actual username
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22
          script: |
            cd public_html
            rm -rf *
            rsync -avzv $GITHUB_WORKSPACE/out/ ./out/
            echo "Deployment complete. Ready to restart PM2."
            pm2 restart all
