name: Deploy to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to StackCP via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com
          username: stephenkingacademy.com
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22
          script: |
            cd public_html
            rm -rf _next public # Remove old files in public_html
            echo "Deployment complete. Ready to restart PM2."
            pm2 restart all
          rsync: true
          source: ./.next/
          target: public_html/.next/ # Correct: Inside public_html
      - uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com
          username: stephenkingacademy.com
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22
          rsync: true
          source: ./public/
          target: public_html/public/ # Correct: Inside public_html