name: Deploy to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build  # This generates the static files and assets

      - name: Check contents of out directory
        run: ls -al $GITHUB_WORKSPACE/out    

      - name: Check remote public_html contents
        run: |
          ssh -i ${{ secrets.STACKCP_PRIVATE_KEY }} stephenkingacademy.com@ssh.us.stackcp.com 'ls -al ~/public_html'

      - name: Deploy to StackCP via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com
          username: stephenkingacademy.com
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Cleaning up public_html directory"
            cd public_html
            rm -rf *  # Ensure all old files are removed
            echo "Syncing out folder contents"
            rsync -avz $GITHUB_WORKSPACE/out/* stephenkingacademy.com@ssh.us.stackcp.com:~/public_html/
            echo "Deployment complete."

      - name: Check remote public_html contents
        run: |
          ssh -i ${{ secrets.STACKCP_PRIVATE_KEY }} stephenkingacademy.com@ssh.us.stackcp.com 'ls -al ~/public_html'