name: Deploy to StackCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: List files before rsync
        run: ls -al .next && ls -al public # Check if the directories exist and have content

      - name: Deploy to StackCP via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ssh.us.stackcp.com
          username: stephenkingacademy.com
          key: ${{ secrets.STACKCP_PRIVATE_KEY }}
          port: 22
          script: |
            cd public_html
            pwd # Print the current working directory on the server
            ls -al # List files in public_html before rsync
            rm -rf _next public
            rsync -avzv .next ./ # VERY VERBOSE rsync
            rsync -avzv public ./ # VERY VERBOSE rsync
            ls -al # List files in public_html after rsync
            echo "Deployment complete. Ready to restart PM2."
            pm2 restart all # Or your start command

      - name: List files after deployment
        run: ssh stephenkingacademy.com@ssh.us.stackcp.com -p 22 -i ${{ secrets.STACKCP_PRIVATE_KEY }} "ls -al public_html"